export { default as Home } from "./Home"
export { default as OnlineLearning } from "./OnlineLearning"
export { default as VipDocuments } from "./VipDocuments"
export { default as Documents } from "./Documents"
export { default as LiveSchedule } from "./LiveSchedule"
export { default as Login } from "./Login"
export { default as Register } from "./Register"
